/* js/map/scenery.js — VAL.Scenery
 * Ascent look: sky dome + sun + clouds + distant floating islands (buildSky),
 * the out-of-bounds Venetian cityscape ring, campanile, basilica and the
 * floating-island rock skirt (buildSurroundings), and the prop library (props.*).
 * Classic script, Three.js r152 global THREE. Uses VAL.Textures.material when present,
 * otherwise plain colour MeshStandardMaterials.
 */
(function () {
  'use strict';
  window.VAL = window.VAL || {};
  const VAL = window.VAL;
  const S = {};
  VAL.Scenery = S;

  // ------------------------------------------------------------------ random / noise
  function makeRng(seed) {
    let a = (seed >>> 0) || 1;
    const r = function () {
      a = (a + 0x6D2B79F5) >>> 0;
      let t = a;
      t = Math.imul(t ^ (t >>> 15), t | 1);
      t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
      return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
    };
    r.range = (lo, hi) => lo + (hi - lo) * r();
    r.int = (lo, hi) => Math.floor(lo + (hi - lo + 1) * r());
    r.pick = (arr) => arr[Math.floor(r() * arr.length) % arr.length];
    r.chance = (p) => r() < p;
    return r;
  }
  // smooth 2π-periodic noise in [-1,1]
  function periodicNoise(rng, octaves) {
    const terms = [];
    let norm = 0;
    for (let k = 1; k <= octaves; k++) { terms.push({ f: k, a: 1 / k, p: rng() * Math.PI * 2 }); norm += 1 / k; }
    return function (theta) {
      let v = 0;
      for (let i = 0; i < terms.length; i++) v += terms[i].a * Math.sin(terms[i].f * theta + terms[i].p);
      return v / norm;
    };
  }

  // ------------------------------------------------------------------ palette
  const SKY = {
    horizon: 0xe9eef2, mid: 0x9ec6e8, zenith: 0x5d9ad4,
    below: 0xd9d6cf, deep: 0xb9c9d8,
    sun: 0xfff6dc, glow: 0xffe4bc
  };
  S.COLORS = {
    horizon: SKY.horizon,
    plaster: [0xe9dcc3, 0xf1ece0, 0xd9a07f, 0xd8b56a, 0xd6a3a0],
    roof: 0xa8563c, brick: 0x9c4b3a, stone: 0xcfc4ae, marble: 0xece8df,
    woodDark: 0x5a3f2c, woodLight: 0xb08a5a, metalDark: 0x3a3d42, teal: 0x2f7f6e,
    foliage: 0x5f9a3d, cypress: 0x2f5e37, rock: 0x6a5c52
  };

  // ------------------------------------------------------------------ materials
  const _plain = new Map();
  function plain(color, opts) {
    opts = opts || {};
    const key = color + '|' + JSON.stringify(opts);
    let m = _plain.get(key);
    if (m) return m;
    m = new THREE.MeshStandardMaterial({
      color: color,
      roughness: opts.roughness !== undefined ? opts.roughness : 0.85,
      metalness: opts.metalness !== undefined ? opts.metalness : 0.0
    });
    if (opts.side !== undefined) m.side = opts.side;
    if (opts.flat) m.flatShading = true;
    if (opts.emissive !== undefined) { m.emissive = new THREE.Color(opts.emissive); m.emissiveIntensity = opts.emissiveIntensity !== undefined ? opts.emissiveIntensity : 1; }
    if (opts.transparent) { m.transparent = true; m.opacity = opts.opacity !== undefined ? opts.opacity : 0.5; m.depthWrite = opts.depthWrite !== undefined ? opts.depthWrite : true; }
    if (opts.fog === false) m.fog = false;
    if (opts.vertexColors) m.vertexColors = true;
    _plain.set(key, m);
    return m;
  }
  // Textured material from VAL.Textures when available, otherwise plain colour fallback.
  // UVs generated by this module are in metres/2 so the 2 m tile repeats correctly with repeat [1,1].
  function mat(name, color, opts) {
    opts = opts || {};
    const T = VAL.Textures;
    if (name && T && typeof T.material === 'function' && (!Array.isArray(T.NAMES) || T.NAMES.indexOf(name) >= 0)) {
      const o = {};
      if (opts.repeat) o.repeat = opts.repeat;
      if (opts.tint !== undefined) o.color = opts.tint;
      if (opts.roughness !== undefined) o.roughness = opts.roughness;
      if (opts.metalness !== undefined) o.metalness = opts.metalness;
      try {
        const m = T.material(name, o);
        if (m && m.isMaterial) return m;
      } catch (e) { /* fall back below */ }
    }
    const po = {};
    if (opts.roughness !== undefined) po.roughness = opts.roughness;
    if (opts.metalness !== undefined) po.metalness = opts.metalness;
    if (opts.side !== undefined) po.side = opts.side;
    if (opts.transparent) { po.transparent = true; po.opacity = opts.opacity; }
    if (opts.emissive !== undefined) { po.emissive = opts.emissive; po.emissiveIntensity = opts.emissiveIntensity; }
    return plain(opts.tint !== undefined ? opts.tint : color, po);
  }
  S.mat = mat;
  S.plain = plain;

  // small canvas textures private to this module (hazard stripes, awning stripes)
  const _canvasTex = new Map();
  function stripeTexture(colorHex, white, vertical) {
    const key = 'stripe' + colorHex + '|' + white + '|' + vertical;
    if (_canvasTex.has(key)) return _canvasTex.get(key);
    const c = document.createElement('canvas'); c.width = c.height = 128;
    const ctx = c.getContext('2d');
    ctx.fillStyle = '#' + (white || 0xf4efe6).toString(16).padStart(6, '0');
    ctx.fillRect(0, 0, 128, 128);
    ctx.fillStyle = '#' + colorHex.toString(16).padStart(6, '0');
    for (let i = 0; i < 4; i++) {
      if (vertical) ctx.fillRect(i * 32, 0, 16, 128); else ctx.fillRect(0, i * 32, 128, 16);
    }
    const t = new THREE.CanvasTexture(c);
    t.colorSpace = THREE.SRGBColorSpace; t.wrapS = t.wrapT = THREE.RepeatWrapping;
    _canvasTex.set(key, t);
    return t;
  }
  function hazardTexture() {
    const key = 'hazard';
    if (_canvasTex.has(key)) return _canvasTex.get(key);
    const c = document.createElement('canvas'); c.width = 128; c.height = 32;
    const ctx = c.getContext('2d');
    ctx.fillStyle = '#e8b323'; ctx.fillRect(0, 0, 128, 32);
    ctx.fillStyle = '#1c1c1c';
    for (let x = -32; x < 160; x += 32) {
      ctx.beginPath(); ctx.moveTo(x, 32); ctx.lineTo(x + 16, 32); ctx.lineTo(x + 32, 0); ctx.lineTo(x + 16, 0); ctx.closePath(); ctx.fill();
    }
    const t = new THREE.CanvasTexture(c);
    t.colorSpace = THREE.SRGBColorSpace; t.wrapS = t.wrapT = THREE.RepeatWrapping;
    _canvasTex.set(key, t);
    return t;
  }
  const _texMats = new Map();
  function texMat(key, tex, opts) {
    if (_texMats.has(key)) return _texMats.get(key);
    const m = new THREE.MeshStandardMaterial(Object.assign({ map: tex, roughness: 0.8, metalness: 0 }, opts || {}));
    _texMats.set(key, m);
    return m;
  }
  function awningMat(colorHex) { return texMat('awn' + colorHex, stripeTexture(colorHex, 0xf4efe6, false), { side: THREE.DoubleSide, roughness: 0.9 }); }
  function hazardMat() { return texMat('hazard', hazardTexture(), { roughness: 0.6, metalness: 0.2 }); }

  // ------------------------------------------------------------------ geometry helpers
  const _m4 = new THREE.Matrix4(), _q = new THREE.Quaternion(), _e = new THREE.Euler(), _v = new THREE.Vector3(), _sc = new THREE.Vector3();
  // apply position / rotation(YXZ order: ry first) / scale to a geometry in place
  function xf(geo, x, y, z, ry, rx, rz, s) {
    _e.set(rx || 0, ry || 0, rz || 0, 'YXZ');
    _q.setFromEuler(_e);
    if (Array.isArray(s)) _sc.set(s[0], s[1], s[2]); else _sc.set(s || 1, s || 1, s || 1);
    _v.set(x || 0, y || 0, z || 0);
    _m4.compose(_v, _q, _sc);
    geo.applyMatrix4(_m4);
    return geo;
  }
  // BoxGeometry with world-scaled UVs (metres / 2) or per-face 0..1 ('face')
  function boxGeo(w, h, d, uvMode) {
    const g = new THREE.BoxGeometry(w, h, d);
    if (uvMode !== 'face') {
      const uv = g.attributes.uv;
      const spans = [[d, h], [d, h], [w, d], [w, d], [w, h], [w, h]];
      for (let f = 0; f < 6; f++) {
        const su = spans[f][0] / 2, sv = spans[f][1] / 2;
        for (let i = 0; i < 4; i++) { const k = f * 4 + i; uv.setXY(k, uv.getX(k) * su, uv.getY(k) * sv); }
      }
      uv.needsUpdate = true;
    }
    return g;
  }
  function planeGeo(w, h) {
    const g = new THREE.PlaneGeometry(w, h);
    const uv = g.attributes.uv;
    for (let i = 0; i < uv.count; i++) uv.setXY(i, uv.getX(i) * w / 2, uv.getY(i) * h / 2);
    return g;
  }
  function cylGeo(rt, rb, h, seg, openEnded) {
    const g = new THREE.CylinderGeometry(rt, rb, h, seg || 12, 1, !!openEnded);
    const uv = g.attributes.uv, circ = Math.PI * (rt + rb);
    const sideCount = 2 * ((seg || 12) + 1);
    for (let i = 0; i < sideCount && i < uv.count; i++) uv.setXY(i, uv.getX(i) * circ / 2, uv.getY(i) * h / 2);
    return g;
  }
  function addColorAttr(geo, hexOrColor) {
    const c = hexOrColor.isColor ? hexOrColor : new THREE.Color(hexOrColor);
    const n = geo.attributes.position.count, arr = new Float32Array(n * 3);
    for (let i = 0; i < n; i++) { arr[i * 3] = c.r; arr[i * 3 + 1] = c.g; arr[i * 3 + 2] = c.b; }
    geo.setAttribute('color', new THREE.BufferAttribute(arr, 3));
    return geo;
  }
  // Merge a list of BufferGeometries (position/normal/uv[/color]) into one. Indexed when all inputs are.
  function mergeGeos(list) {
    if (!list || !list.length) return null;
    let indexed = true, hasColor = false;
    for (const g of list) { if (!g.index) indexed = false; if (g.attributes.color) hasColor = true; }
    let vCount = 0, iCount = 0;
    const geos = [];
    for (let g of list) {
      if (!indexed && g.index) g = g.toNonIndexed();
      if (!g.attributes.normal) g.computeVertexNormals();
      vCount += g.attributes.position.count;
      if (indexed) iCount += g.index.count;
      geos.push(g);
    }
    const pos = new Float32Array(vCount * 3), nor = new Float32Array(vCount * 3), uv = new Float32Array(vCount * 2);
    const col = hasColor ? new Float32Array(vCount * 3) : null;
    const idx = indexed ? (vCount > 65535 ? new Uint32Array(iCount) : new Uint16Array(iCount)) : null;
    let vo = 0, io = 0;
    for (const g of geos) {
      const n = g.attributes.position.count;
      pos.set(g.attributes.position.array.subarray(0, n * 3), vo * 3);
      nor.set(g.attributes.normal.array.subarray(0, n * 3), vo * 3);
      if (g.attributes.uv) uv.set(g.attributes.uv.array.subarray(0, n * 2), vo * 2);
      if (hasColor) {
        if (g.attributes.color) col.set(g.attributes.color.array.subarray(0, n * 3), vo * 3);
        else col.fill(1, vo * 3, (vo + n) * 3);
      }
      if (indexed) { const ia = g.index.array; for (let i = 0; i < ia.length; i++) idx[io + i] = ia[i] + vo; io += ia.length; }
      vo += n;
    }
    const out = new THREE.BufferGeometry();
    out.setAttribute('position', new THREE.BufferAttribute(pos, 3));
    out.setAttribute('normal', new THREE.BufferAttribute(nor, 3));
    out.setAttribute('uv', new THREE.BufferAttribute(uv, 2));
    if (hasColor) out.setAttribute('color', new THREE.BufferAttribute(col, 3));
    if (indexed) out.setIndex(new THREE.BufferAttribute(idx, 1));
    return out;
  }
  S._mergeGeos = mergeGeos;

  // Parts collector: add transformed geometries per material, then build merged meshes into a group.
  function Parts() { this.map = new Map(); this.list = []; }
  Parts.prototype.add = function (geo, material, x, y, z, ry, rx, rz, s) {
    xf(geo, x, y, z, ry, rx, rz, s);
    let arr = this.map.get(material);
    if (!arr) { arr = []; this.map.set(material, arr); this.list.push(material); }
    arr.push(geo);
    return geo;
  };
  Parts.prototype.build = function (group, shadows) {
    for (const m of this.list) {
      const g = mergeGeos(this.map.get(m));
      if (!g) continue;
      const mesh = new THREE.Mesh(g, m);
      if (shadows !== false) { mesh.castShadow = true; mesh.receiveShadow = true; }
      group.add(mesh);
    }
    return group;
  };
  S._Parts = Parts;

  // objects animated by the sky update loop (rock fragments etc.), shared across builders
  const _animated = [];

  // ------------------------------------------------------------------ sky
  const SKY_VERT = [
    'varying vec3 vWorld;',
    'void main(){',
    '  vec4 wp = modelMatrix * vec4(position, 1.0);',
    '  vWorld = wp.xyz;',
    '  gl_Position = projectionMatrix * viewMatrix * wp;',
    '}'
  ].join('\n');
  const SKY_FRAG = [
    'uniform vec3 horizon, mid, zenith, below, deep, sunColor, glowColor, sunDir;',
    'varying vec3 vWorld;',
    'float hash(vec2 p){ return fract(sin(dot(p, vec2(12.9898, 78.233))) * 43758.5453); }',
    'void main(){',
    '  vec3 d = normalize(vWorld - cameraPosition);',
    '  float h = d.y;',
    '  vec3 col;',
    '  if (h >= 0.0) {',
    '    col = mix(horizon, mid, smoothstep(0.0, 0.24, h));',
    '    col = mix(col, zenith, smoothstep(0.16, 0.78, h));',
    '  } else {',
    '    col = mix(horizon, below, smoothstep(0.0, -0.07, h));',
    '    col = mix(col, deep, smoothstep(-0.05, -0.45, h));',
    '  }',
    '  float sd = max(dot(d, normalize(sunDir)), 0.0);',
    '  col += glowColor * (pow(sd, 5.0) * 0.14 + pow(sd, 48.0) * 0.32);',
    '  col += sunColor * smoothstep(0.995, 0.9997, sd) * 0.45;',
    '  col = mix(col, sunColor, smoothstep(0.99925, 0.99965, sd));',
    '  col += (hash(gl_FragCoord.xy) - 0.5) / 255.0;',
    '  gl_FragColor = vec4(col, 1.0);',
    '  #include <tonemapping_fragment>',
    '  #include <encodings_fragment>',
    '}'
  ].join('\n');

  function cloudTexture(seed) {
    const w = 256, h = 128, c = document.createElement('canvas'); c.width = w; c.height = h;
    const ctx = c.getContext('2d'); const r = makeRng(seed);
    const n = 10 + Math.floor(r() * 6);
    for (let i = 0; i < n; i++) {
      const cx = w * 0.18 + r() * w * 0.64, cy = h * 0.42 + r() * h * 0.3, rad = h * (0.17 + r() * 0.22);
      const g = ctx.createRadialGradient(cx, cy, 0, cx, cy, rad);
      g.addColorStop(0, 'rgba(255,255,255,0.95)');
      g.addColorStop(0.5, 'rgba(255,252,253,0.6)');
      g.addColorStop(1, 'rgba(255,255,255,0)');
      ctx.fillStyle = g; ctx.fillRect(cx - rad, cy - rad, rad * 2, rad * 2);
    }
    ctx.globalCompositeOperation = 'source-atop';
    const sh = ctx.createLinearGradient(0, h * 0.3, 0, h);
    sh.addColorStop(0, 'rgba(255,255,255,0)'); sh.addColorStop(1, 'rgba(205,170,200,0.6)');
    ctx.fillStyle = sh; ctx.fillRect(0, 0, w, h);
    ctx.globalCompositeOperation = 'source-over';
    const tex = new THREE.CanvasTexture(c); tex.colorSpace = THREE.SRGBColorSpace;
    return tex;
  }

  // distant floating island: rock chunk with flat top, spikes below, tiny buildings. One merged mesh, vertex colours.
  function skyIslandGeometry(rng, R, hazeColor, hazeAmt) {
    const geos = [];
    const rockCol = new THREE.Color(0x5b4f47).lerp(hazeColor, hazeAmt);
    const rockDark = new THREE.Color(0x46403c).lerp(hazeColor, hazeAmt * 0.9);
    const N = 11, noise = periodicNoise(rng, 4);
    const rings = [
      { y: 0, k: 1.0 }, { y: -R * 0.22, k: 1.08 }, { y: -R * 0.55, k: 0.78 }, { y: -R * 0.95, k: 0.42 }, { y: -R * 1.3, k: 0.12 }
    ];
    const pts = rings.map((rg, ri) => {
      const arr = [];
      for (let i = 0; i < N; i++) {
        const th = i / N * Math.PI * 2;
        const rad = R * rg.k * (1 + 0.28 * noise(th + ri * 0.7)) * (0.92 + rng() * 0.16);
        arr.push(new THREE.Vector3(Math.cos(th) * rad, rg.y + (ri ? (rng() - 0.5) * R * 0.08 : 0), Math.sin(th) * rad));
      }
      return arr;
    });
    const tri = [];
    function pushTri(a, b, c) { tri.push(a.x, a.y, a.z, b.x, b.y, b.z, c.x, c.y, c.z); }
    // top cap (fan, faces up)
    const top = new THREE.Vector3(0, 0, 0);
    for (let i = 0; i < N; i++) pushTri(top, pts[0][(i + 1) % N], pts[0][i]);
    for (let r = 0; r < rings.length - 1; r++) {
      for (let i = 0; i < N; i++) {
        const a = pts[r][i], b = pts[r][(i + 1) % N], c = pts[r + 1][(i + 1) % N], d = pts[r + 1][i];
        pushTri(a, b, c); pushTri(a, c, d);
      }
    }
    const bottom = new THREE.Vector3((rng() - 0.5) * R * 0.2, -R * 1.5, (rng() - 0.5) * R * 0.2);
    const last = pts[rings.length - 1];
    for (let i = 0; i < N; i++) pushTri(last[i], last[(i + 1) % N], bottom);
    const rock = new THREE.BufferGeometry();
    rock.setAttribute('position', new THREE.BufferAttribute(new Float32Array(tri), 3));
    rock.computeVertexNormals();
    // colour: top faces lighter rock, sides darker
    const nrm = rock.attributes.normal, cnt = rock.attributes.position.count, colArr = new Float32Array(cnt * 3);
    for (let i = 0; i < cnt; i++) {
      const up = Math.max(0, nrm.getY(i));
      const c = rockDark.clone().lerp(rockCol, up);
      colArr[i * 3] = c.r; colArr[i * 3 + 1] = c.g; colArr[i * 3 + 2] = c.b;
    }
    rock.setAttribute('color', new THREE.BufferAttribute(colArr, 3));
    rock.setAttribute('uv', new THREE.BufferAttribute(new Float32Array(cnt * 2), 2));
    geos.push(rock);
    // hanging spikes
    const nsp = 3 + rng.int(0, 4);
    for (let i = 0; i < nsp; i++) {
      const th = rng() * Math.PI * 2, rr = R * rng.range(0.15, 0.7);
      const sh = R * rng.range(0.5, 1.1), sr = R * rng.range(0.06, 0.13);
      const g = new THREE.ConeGeometry(sr, sh, 5, 1);
      xf(g, Math.cos(th) * rr, -R * 0.45 - sh / 2, Math.sin(th) * rr, rng() * 6.28, Math.PI + (rng() - 0.5) * 0.25, (rng() - 0.5) * 0.25);
      addColorAttr(g.toNonIndexed(), rockDark);
      const gg = g.toNonIndexed(); gg.computeVertexNormals(); addColorAttr(gg, rockDark); geos.push(gg);
    }
    // tiny buildings on top
    const nb = rng.chance(0.15) ? 0 : rng.int(3, 9);
    const plasters = [0xe9dcc3, 0xf1ece0, 0xd9a07f, 0xd8b56a, 0xd6a3a0];
    for (let i = 0; i < nb; i++) {
      const th = rng() * Math.PI * 2, rr = R * rng.range(0, 0.55);
      const bw = rng.range(3, 7), bd = rng.range(3, 7), bh = rng.range(3, 9), ry = rng() * Math.PI;
      const wall = new THREE.Color(rng.pick(plasters)).lerp(hazeColor, hazeAmt);
      const roofc = new THREE.Color(0xa8563c).lerp(hazeColor, hazeAmt);
      const bx = Math.cos(th) * rr, bz = Math.sin(th) * rr;
      const b = new THREE.BoxGeometry(bw, bh, bd); xf(b, bx, bh / 2 - 0.3, bz, ry); addColorAttr(b, wall); geos.push(b);
      const roof = new THREE.ConeGeometry(Math.max(bw, bd) * 0.72, Math.min(bw, bd) * 0.45, 4, 1);
      xf(roof, bx, bh - 0.3 + Math.min(bw, bd) * 0.225, bz, ry + Math.PI / 4); const rg = roof.toNonIndexed(); rg.computeVertexNormals(); addColorAttr(rg, roofc); geos.push(rg);
    }
    if (nb > 4 && rng.chance(0.5)) { // a little tower
      const th = rng() * Math.PI * 2, rr = R * rng.range(0.1, 0.4), tw = rng.range(2.5, 3.5), tH = rng.range(12, 20);
      const t = new THREE.BoxGeometry(tw, tH, tw); xf(t, Math.cos(th) * rr, tH / 2 - 0.3, Math.sin(th) * rr);
      addColorAttr(t, new THREE.Color(0x9c4b3a).lerp(hazeColor, hazeAmt)); geos.push(t);
      const cap = new THREE.ConeGeometry(tw * 0.8, tw * 1.2, 4, 1); xf(cap, Math.cos(th) * rr, tH - 0.3 + tw * 0.6, Math.sin(th) * rr, Math.PI / 4);
      const cg = cap.toNonIndexed(); cg.computeVertexNormals(); addColorAttr(cg, new THREE.Color(0x3c8a6e).lerp(hazeColor, hazeAmt)); geos.push(cg);
    }
    return mergeGeos(geos.map(g => g.index ? g.toNonIndexed() : g));
  }

  S.buildSky = function (scene, renderer) {
    const rng = makeRng(20240613);
    const horizon = new THREE.Color(SKY.horizon);
    scene.background = horizon.clone();
    scene.fog = new THREE.Fog(horizon.clone(), 60, 260);

    const group = new THREE.Group(); group.name = 'sky';
    scene.add(group);

    // -- gradient dome (follows the camera, drawn first, ignores depth so its radius does not matter)
    const sunDir = new THREE.Vector3(-0.62, 0.30, 0.72).normalize(); // toward the sun: low south-west
    const uniforms = {
      horizon: { value: horizon.clone() }, mid: { value: new THREE.Color(SKY.mid) }, zenith: { value: new THREE.Color(SKY.zenith) },
      below: { value: new THREE.Color(SKY.below) }, deep: { value: new THREE.Color(SKY.deep) },
      sunColor: { value: new THREE.Color(SKY.sun) }, glowColor: { value: new THREE.Color(SKY.glow) },
      sunDir: { value: sunDir.clone() }
    };
    const skyMat = new THREE.ShaderMaterial({ uniforms, vertexShader: SKY_VERT, fragmentShader: SKY_FRAG, side: THREE.BackSide, depthWrite: false, depthTest: false, fog: false });
    const dome = new THREE.Mesh(new THREE.SphereGeometry(40, 32, 20), skyMat);
    dome.name = 'skyDome'; dome.renderOrder = -1000; dome.frustumCulled = false;
    dome.matrixAutoUpdate = true;
    const camPos = new THREE.Vector3();
    dome.onBeforeRender = function (r, sc, camera) {
      camera.getWorldPosition(camPos);
      dome.position.copy(camPos);
      dome.updateMatrixWorld(true);
    };
    group.add(dome);

    // -- clouds (sprites, no fog: they carry their own haze tint)
    const cloudTex = [cloudTexture(11), cloudTexture(23), cloudTexture(37)];
    const clouds = [];
    const cloudGroup = new THREE.Group(); cloudGroup.name = 'clouds'; group.add(cloudGroup);
    function addCloud(theta, dist, y, w, opacity, tint) {
      const m = new THREE.SpriteMaterial({ map: rng.pick(cloudTex), transparent: true, opacity: opacity, depthWrite: false, fog: false, color: tint });
      const sp = new THREE.Sprite(m);
      sp.position.set(Math.cos(theta) * dist, y, Math.sin(theta) * dist);
      sp.scale.set(w, w * 0.5, 1);
      sp.userData = { theta, dist, y0: y, speed: rng.range(0.004, 0.009), bob: rng() * 6.28 };
      cloudGroup.add(sp); clouds.push(sp);
      return sp;
    }
    for (let i = 0; i < 9; i++) { // low cloud banks below the island rim
      const th = i / 9 * Math.PI * 2 + rng.range(-0.25, 0.25);
      addCloud(th, rng.range(170, 300), rng.range(-70, -30), rng.range(260, 420), 0.92, 0xf6ecf2);
    }
    for (let i = 0; i < 8; i++) { // cumulus around the horizon
      const th = i / 8 * Math.PI * 2 + rng.range(-0.3, 0.3) + 0.4;
      addCloud(th, rng.range(260, 380), rng.range(-5, 45), rng.range(120, 220), 0.85, 0xfaf1f5);
    }
    for (let i = 0; i < 4; i++) { // a few high wisps
      addCloud(rng() * 6.28, rng.range(280, 380), rng.range(70, 130), rng.range(160, 240), 0.55, 0xf3e6ee);
    }

    // -- distant floating islands
    const islandMat = new THREE.MeshStandardMaterial({ vertexColors: true, roughness: 0.95, metalness: 0, fog: false });
    islandMat.flatShading = true;
    const islands = [];
    const nIsl = 9;
    for (let i = 0; i < nIsl; i++) {
      const th = i / nIsl * Math.PI * 2 + rng.range(-0.2, 0.2) + 0.15;
      const dist = rng.range(170, 380);
      const haze = 0.42 + 0.4 * (dist - 170) / 210;
      const R = rng.range(16, 44) * (dist > 300 ? 1.3 : 1);
      const geo = skyIslandGeometry(rng, R, horizon, haze);
      const mesh = new THREE.Mesh(geo, islandMat);
      const y = rng.chance(0.5) ? rng.range(-45, -10) : rng.range(10, 70);
      mesh.position.set(Math.cos(th) * dist, y, Math.sin(th) * dist);
      mesh.rotation.y = rng() * 6.28;
      mesh.userData = { theta: th, dist, y0: y, bobAmp: rng.range(1.2, 3), bobRate: rng.range(0.04, 0.09), phase: rng() * 6.28, drift: rng.range(0.0008, 0.0018) };
      mesh.frustumCulled = true;
      group.add(mesh); islands.push(mesh);
    }

    let t = 0;
    const api = {
      group, dome, clouds, islands, sunDir,
      setSunDirection(dir) { if (dir) { sunDir.copy(dir).normalize(); uniforms.sunDir.value.copy(sunDir); } },
      update(dt, dir) {
        dt = Math.min(dt || 0, 0.1); t += dt;
        if (dir && dir.isVector3) api.setSunDirection(dir);
        for (const c of clouds) {
          const u = c.userData; u.theta += u.speed * dt;
          c.position.set(Math.cos(u.theta) * u.dist, u.y0 + Math.sin(t * 0.05 + u.bob) * 3, Math.sin(u.theta) * u.dist);
        }
        for (const m of islands) {
          const u = m.userData; u.theta += u.drift * dt;
          m.position.set(Math.cos(u.theta) * u.dist, u.y0 + Math.sin(t * u.bobRate + u.phase) * u.bobAmp, Math.sin(u.theta) * u.dist);
        }
        for (let i = 0; i < _animated.length; i++) _animated[i](dt, t);
      }
    };
    return api;
  };

  // (surroundings and props follow)

})();
